FROM devilbox/php-fpm:8.0-work

USER root
RUN set -ex; \
    \
    ln --symbolic /opt/nvm/versions/node/*/bin/pnpm /usr/local/bin/pnpm; \
    \
    apt-get update; \
    apt-get install --assume-yes --no-install-recommends \
        libzmq3-dev; \
    \
# Install php-zmq
    cd /usr; \
    curl \
        --location https://github.com/zeromq/php-zmq/archive/ee5fbc693f07b2d6f0d9fd748f131be82310f386.tar.gz \
        --output php-zmq.tar.gz \
        --fail \
        --silent \
        --show-error; \
    tar -z --extract --file php-zmq.tar.gz; \
    cd php-zmq*; \
    phpize && ./configure; \
    make; \
    make install; \
    cd .. && rm --recursive --force php-zmq*; \
# END: Install php-zmq
    docker-php-ext-enable zmq;

COPY --chmod=0755 common/docker-*.sh  /usr/local/bin/