---
version: '3'

################################################################################
# SERVICES
################################################################################
services:
  # ------------------------------------------------------------
  # Traefik Reverse Proxy
  # ------------------------------------------------------------
  traefik:
    image: traefik:${TRAEFIK_VERSION:-2.9}
    container_name: traefik
    restart: unless-stopped

    ports:
      - '127.0.0.1:${HTTP_PORT:-8080}:80'

    command:
      - --log.level=DEBUG

      - --entrypoints.http.address=:80
      - --entryPoints.http.forwardedheaders.insecure

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --api=false
      - --api.insecure=false
      - --api.dashboard=false

      - --global.sendanonymoususage=false
      - --global.checknewversion=false
      - --pilot.dashboard=false

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # ------------------------------------------------------------
  # PHP
  # ------------------------------------------------------------
  php: &php
    build:
      context: ./docker/php
      dockerfile: Dockerfile-8.0
    container_name: php
    hostname: php
    restart: unless-stopped

    environment:
      DEBUG_ENTRYPOINT: '2'
      DEBUG_COMPOSE_ENTRYPOINT: '2'
      DOCKER_LOGS: '1'
      COMPOSER_MEMORY_LIMIT: '-1'

    volumes:
      - .:/shared/httpd:rw

      # Users SSH directory (read-only)
      - ${SSH_AUTH_SOCK_DIR:-/dev/null}:${SSH_AUTH_SOCK_DIR:-/dev/null}
      - ~/.ssh:/home/devilbox/.ssh:ro

      # Users .bash_history file
      - ~/.bash_history:/home/devilbox/.bash_history:rw

  # ------------------------------------------------------------
  # Daemon
  # ------------------------------------------------------------
  daemon:
    <<: *php
    container_name: daemon
    entrypoint: docker-daemon.sh
    user: devilbox:devilbox

  # ------------------------------------------------------------
  # EspoCRM Console
  # ------------------------------------------------------------
  espo-console:
    <<: *php
    build: ./docker/espo-console
    container_name: espo-console

  # ------------------------------------------------------------
  # Web Server
  # ------------------------------------------------------------
  httpd:
    image: nginx:${NGINX_VERSION:-stable-alpine}
    container_name: httpd
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    volumes:
      - .:/shared/httpd:ro
      - ./docker/cfg/nginx/espo.conf:/etc/nginx/conf.d/default.conf:ro

    labels:
      - traefik.enable=true
      - traefik.http.routers.espocrm.rule=Host(`localhost`)
      - traefik.http.routers.espocrm.entrypoints=http
      - traefik.http.routers.espocrm.service=espocrm-service
      - traefik.http.services.espocrm-service.loadbalancer.server.port=80

    depends_on:
      - php

  # ------------------------------------------------------------
  # MySQL Database
  # ------------------------------------------------------------
  mysql:
    image: mariadb:${MYSQL_VERSION:-10.6}
    container_name: mysql
    hostname: mysql
    restart: unless-stopped

    ports:
      - '127.0.0.1:3306:3306'

    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10

    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: '${MYSQL_ALLOW_EMPTY_PASSWORD:-yes}'
      MYSQL_USER: '${MYSQL_PASSWORD:-espocrm}'
      MYSQL_DATABASE: '${MYSQL_DATABASE:-espocrm}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-espocrm}'

    volumes:
      - mysql:/var/lib/mysql:rw

volumes:
  mysql: {}