---
version: '3'

################################################################################
# SERVICES
################################################################################
services:
  # ------------------------------------------------------------
  # Traefik Reverse Proxy
  # ------------------------------------------------------------
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always

    ports:
      - "${HTTP_PORT:-8080}:80"

    command:
      - --log.level=DEBUG

      - --entrypoints.http.address=:80
      - --entryPoints.http.forwardedheaders.insecure

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --api=false
      - --api.insecure=false
      - --api.dashboard=false

      - --global.sendanonymoususage=false
      - --global.checknewversion=false
      - --pilot.dashboard=false

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # ------------------------------------------------------------
  # PHP
  # ------------------------------------------------------------
  php:
    image: devilbox/php-fpm:8.0-work
    container_name: php
    hostname: php

    working_dir: /var/www/default

    environment:
      - COMPOSER_MEMORY_LIMIT=-1

    volumes:
      - $PWD:/var/www/default:rw

      # Users SSH directory (read-only)
      - ${HOME}/.ssh:/home/devilbox/.ssh:ro

      # Users .bash_history file
      - ${HOME}/.bash_history:/home/devilbox/.bash_history:rw

  # ------------------------------------------------------------
  # Web Server
  # ------------------------------------------------------------
  httpd:
    image: devilbox/apache-2.4:latest
    container_name: httpd
    restart: always
    hostname: httpd

    environment:
      - MAIN_VHOST_DOCROOT=site
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=180

    volumes:
      - $PWD:/var/www/default:rw

    labels:
      - traefik.enable=true
      - traefik.http.routers.espocrm.rule=Host(`localhost`)
      - traefik.http.routers.espocrm.entrypoints=http

  # ------------------------------------------------------------
  # MySQL Database
  # ------------------------------------------------------------
  mysql:
    image: devilbox/mysql:mariadb-10.5
    container_name: mysql
    hostname: mysql

    ports:
      - "3${HTTP_PORT:-8080}:3306"

    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD:-yes}

    volumes:
      - mysql:/var/lib/mysql:rw

  # ------------------------------------------------------------
  # Fake SMTP server
  # ------------------------------------------------------------
  # maildev:
  #   image: maildev/maildev:latest
  #   container_name: maildev
  #   hostname: maildev
  #   restart: always

  #   environment:
  #     - TZ=Europe/Warsaw
  #     - MAILDEV_WEB_PORT=1080
  #     - MAILDEV_SMTP_PORT=25

  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.maildev.rule=Host(`mail.localhost`)
  #     - traefik.http.routers.maildev.entrypoints=http
  #     - traefik.http.routers.maildev.service=maildev-service
  #     - traefik.http.services.maildev-service.loadbalancer.server.port=1080

  # ------------------------------------------------------------
  # Fake SMTP server
  # ------------------------------------------------------------
  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev
    hostname: smtp4dev
    restart: always

    environment:
      - ServerOptions__HostName=smtp4dev

    labels:
      - traefik.enable=true
      - traefik.http.routers.smtp4dev.rule=Host(`mail.localhost`)
      - traefik.http.routers.smtp4dev.entrypoints=http
      - traefik.http.routers.smtp4dev.service=smtp4dev-service
      - traefik.http.services.smtp4dev-service.loadbalancer.server.port=80

    volumes:
      - smtp4dev-data:/smtp4dev

  # ------------------------------------------------------------
  # phpMyAdmin
  # ------------------------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always

    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=

    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(`pma.localhost`)
      - traefik.http.routers.phpmyadmin.entrypoints=http

    depends_on:
      - mysql

  # -----------------------------------------------------------------------------------------------
  # Ngrok
  # -----------------------------------------------------------------------------------------------
  ngrok:
    image: wernight/ngrok:latest
    container_name: ngrok

    environment:
      - NGROK_PORT=httpd:80
      - NGROK_REGION=${NGROK_REGION:-eu}
      - NGROK_AUTH=${NGROK_AUTH:-}

    labels:
      - traefik.enable=true
      - traefik.http.routers.ngrok.rule=Host(`ngrok.localhost`)
      - traefik.http.routers.ngrok.entrypoints=http
      - traefik.http.services.ngrok.loadbalancer.server.port=4040

    depends_on:
      - espocrm

volumes:
  mysql: null
  smtp4dev-data: null
