---
version: '3'

################################################################################
# VOLUMES
################################################################################
volumes:
  mysql: {}

################################################################################
# SERVICES
################################################################################
services:
  # ------------------------------------------------------------
  # PHP
  # ------------------------------------------------------------
  php:
    image: devilbox/php-fpm:8.1-work
    container_name: php
    working_dir: /var/www/default
    volumes: [.:/var/www/default:rw]
    environment:
      NEW_UID: 1000
      NEW_GID: 1000
      DEBUG_ENTRYPOINT: '2'
      DEBUG_COMPOSE_ENTRYPOINT: '2'
      DOCKER_LOGS: '1'
      COMPOSER_MEMORY_LIMIT: '-1'
      COMPOSER_POOL_OPTIMIZER: '0'

  # ------------------------------------------------------------
  # Web Server
  # ------------------------------------------------------------
  httpd:
    image: devilbox/apache-2.4:alpine
    container_name: httpd
    ports: [8080:80]
    volumes: [.:/var/www/default:ro]
    depends_on: [php]
    environment:
      MAIN_VHOST_DOCROOT_DIR: site
      MAIN_VHOST_BACKEND: conf:phpfpm:tcp:php:9000

  # ------------------------------------------------------------
  # MySQL Database
  # ------------------------------------------------------------
  mysql:
    image: mariadb:${MYSQL_VERSION:-lts}
    container_name: mysql
    restart: unless-stopped
    ports: [3306:3306]
    volumes: [mysql:/var/lib/mysql:rw]
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-yes}
      MYSQL_USER: ${MYSQL_PASSWORD:-espocrm}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-espocrm}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-espocrm}
